/******************************************************************************/
/*           Generated by IBExpert 2023.4.14.1 16/11/2023 14:28:15            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ISO8859_1;

SET CLIENTLIB 'C:\Program Files (x86)\Firebird\Firebird_3_0\fbclient.dll';

CREATE DATABASE 'D:\PostoABC\DataBase\BANCO.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET ISO8859_1 COLLATION ISO8859_1;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE ABASTECIMENTO (
    ID                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    DATA                DATE NOT NULL,
    ID_BOMBA            INTEGER NOT NULL,
    QUANTIDADE_LITROS   DOUBLE PRECISION,
    PRECO               DOUBLE PRECISION,
    PERCENTUAL_IMPOSTO  DOUBLE PRECISION,
    VALOR               DOUBLE PRECISION
);

CREATE TABLE BOMBA (
    ID         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NUMERO     INTEGER NOT NULL,
    PRECO      DOUBLE PRECISION,
    ID_TANQUE  INTEGER NOT NULL
);

CREATE TABLE IMPOSTO (
    ID          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    PERCENTUAL  DOUBLE PRECISION NOT NULL
);

CREATE TABLE TANQUE (
    ID           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    DESCRICAO    VARCHAR(100),
    COMBUSTIVEL  INTEGER
);



/******************************************************************************/
/*                          Autoincrement generators                          */
/******************************************************************************/

ALTER TABLE ABASTECIMENTO ALTER ID RESTART WITH 11;
ALTER TABLE BOMBA ALTER ID RESTART WITH 3;
ALTER TABLE IMPOSTO ALTER ID RESTART WITH 4;
ALTER TABLE TANQUE ALTER ID RESTART WITH 4;




/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT PK_ABASTECIMENTO PRIMARY KEY (ID);
ALTER TABLE BOMBA ADD CONSTRAINT PK_BOMBA PRIMARY KEY (ID);
ALTER TABLE IMPOSTO ADD CONSTRAINT PK_IMPOSTO PRIMARY KEY (ID);
ALTER TABLE TANQUE ADD CONSTRAINT PK_TANQUE PRIMARY KEY (ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_1 FOREIGN KEY (ID_BOMBA) REFERENCES BOMBA (ID);
ALTER TABLE BOMBA ADD CONSTRAINT FK_BOMBA_1 FOREIGN KEY (ID_TANQUE) REFERENCES TANQUE (ID);
